server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/task?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        ddl-auto: update #启动hibernate时会自动检查数据库，如果缺少表，则自动建表；如果表里缺少列，则自动添加列。
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  transaction:
      rollback-on-commit-failure: true #事务回滚hibernate.transaction.auto_close_session=true
  redis:
    host: localhost
    port: 6379
    max-wait: 30000 #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100 #连接池最大连接数（使用负值表示没有限制）
    max-idle: 20 #连接池中最大的空间连接
    min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000 #连接超时
    maxmemory-policy: allkeys-lru #当内存不足以容纳新写入数据时，在键空间中，移除最近最少使用的key
  servlet:
    multipart:
      max-file-size: 10MB # maxFileSize 单个数据大小
      max-request-size: 100MB # maxRequestSize 是总数据大小
system:
  upload: upload/import/
# JWT
jwt:
  header: token
  secret: mySecret
  expiration: 86400000 #1000*60*60一小时
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth/getToken
      refresh: auth/refreshToken
      register: "auth/register"



